### ISSUE TITLE
Creating a video phrase in an empty book does not work

### ISSUE THREAD

**Issue by FredericoAndrade** [wikitongues/poly#120]
![new book video bug](https://cloud.githubusercontent.com/assets/2080065/19575118/0d1f0a74-96db-11e6-9df3-a1d4e1909826.gif)

When in an empty book, creating a video phrase first does not work. Refer to gif ^

**Comment by bjlaa** [comment]
Hmm interesting. Let me get a look at this; should fairly simple to fix

**Comment by bjlaa** [comment]
Okay, it works now. Made a GIF to show you how I'd done it.
![oct -21-2016 10-19-45](https://cloud.githubusercontent.com/assets/12382534/19591616/329a1184-9778-11e6-9305-45b87ce0918d.gif)

I'm gonna go ahead and close this now :)
