### ISSUE TITLE
User should be able to record a video for the description of the book

### ISSUE THREAD

**Issue by FredericoAndrade** [wikitongues/poly#142]
Example interface: ![image](https://cloud.githubusercontent.com/assets/2080065/20734499/e515555e-b667-11e6-8ad0-73e95166a348.png)

**Comment by FredericoAndrade** [comment]
@bjlaa closing this issue, and the branch https://github.com/wikitongues/poly/tree/142-book-description as feature has been published separately

**Comment by bjlaa** [comment]
Okay, np :)

2017-03-21 20:52 GMT+01:00 Frederico Andrade <notifications@github.com>:
