### ISSUE TITLE
Password reset email bug

### ISSUE THREAD

**Issue by ErinGreenhalgh** [wikitongues/poly#152]
**Bug Description:**
* on `sign_in` page, users can click a "Forgot your password?" link that redirects to `/password/new`
* entering an email and clicking the button causes a rails error:
<img width="1370" alt="screen shot 2016-12-17 at 11 52 17 am" src="https://cloud.githubusercontent.com/assets/16656094/21289038/927971f4-c44f-11e6-9800-a31197bcb883.png">

**Fix:**
* users should be able to enter their email, receive a notification that the email was sent, and follow the directions in the email to reset their password.

**Comment by FredericoAndrade** [comment]
@ErinGreenhalgh this happens due to a lack of keys. Happy to send you the keys (necessary for video feature too)!
