### ISSUE TITLE
Top menu covers page content

### ISSUE THREAD

**Issue by psubhashish** [wikitongues/poly#211]
![The top menu covering a page's content](https://cloud.githubusercontent.com/assets/1258090/25061589/97f82766-21d7-11e7-96d9-f3857bfd96f2.PNG)
As you see in the screenshot above, the top menu with three items - "Roadmap", "Sign up" and "Log in" are covering [subtly] the page content which might be a troubling feature especially for those with accessibility needs [as they would be using screenreader to interact with the phone].

One alternative can be having a small icon on the top left/right that one can tap to see the subpages.

**Comment by FredericoAndrade** [comment]
@psubhashish fixed, thanks!

**Comment by psubhashish** [comment]
Thanks @FredericoAndrade
