### ISSUE TITLE
valid-input checking for phrase input

### ISSUE THREAD

**Issue by procrastinatrix** [wikitongues/poly#22]
When the user hits "submit" for either the source or target phrases, there is no check on whether the inputted string was empty, so you can create empty phrases in the database.

**Comment by procrastinatrix** [comment]
I added a simple check for non-zero length strings for both inputs. There's no malicious-entry checking at all.

**Comment by FredericoAndrade** [comment]
fixed with https://github.com/wikitongues/poly/commit/3fa91f8fc2eab868c2aff3f76d5e505402f4631d
