### ISSUE TITLE
Set up a staging environment

### ISSUE THREAD

**Issue by FredericoAndrade** [wikitongues/poly#221]
Set up a live staging environment to 
  a. test new features live
  b. have a safe environment to try new things 

@ChrisVoxland Feel like helping out?

**Comment by ChrisVoxland** [comment]
yar, happy to help out with this. should have time later this week or next week in the evening/afternoon if you want to pair on it

**Comment by FredericoAndrade** [comment]
Nice, would love that! Lemme know when works for you?
