### ISSUE TITLE
Edited phrases occasionally fail to render during continuous entry

### ISSUE THREAD

**Issue by bogreudell** [wikitongues/poly#60]

**Comment by FredericoAndrade** [comment]
steps: 
1. enable continuous entry
2. edit an existing phrase pair
3. enter a new phrase
![poly edit bug](https://cloud.githubusercontent.com/assets/2080065/18886317/6b84fc34-84bd-11e6-8a4f-00542dffa568.gif)

**Comment by FredericoAndrade** [comment]
related to https://github.com/wikitongues/poly/issues/139
